### ISSUE TITLE
Bug: Lola's 8 Heart Recipe Keeps Appearing

### ISSUE THREAD

**Issue by dogwolf12** [Rafseazz/Ridgeside-Village-Mod#166]
Hi,
As the title says, when I reached 8 hearts with Lola, I got the recipe in the mail - but when I closed it, the letter symbol was still there, and clicking on it still yielded the same letter, no matter how many times I clicked. Going to a new day did not resolve the issue. 
I have updated all mods to their latest version, including Ridgeside, and have no known incompatibilities.
How to reproduce: reach 8 hearts with Lola, and open the letter.

**Comment by cl4r3** [comment]
This is a glitch caused by the outdated mod FeTK, which has been replaced by MFM. Please uninstall it, and report any future issues either to the Nexus page or our Discord server.

**Comment by dogwolf12** [comment]
Thanks!
